# Generated by Django 3.1.1 on 2021-03-02 22:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='books/covers/'),
        ),
        migrations.AddField(
            model_name='post',
            name='pdf',
            field=models.FileField(default=django.utils.timezone.now, upload_to='books/pdfs/'),
            preserve_default=False,
        ),
    ]
