# Generated by Django 3.1.1 on 2021-03-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210302_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='book_author',
            field=models.TextField(default='No Author', max_length=225),
        ),
    ]
